---
language: node_js
<<<<<<< HEAD
||||||| parent of a330f96... message
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "4"

=======
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

>>>>>>> a330f96... message
sudo: false
dist: trusty
node_js: 'stable'

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
<<<<<<< HEAD
  # we recommend new addons test the current and previous LTS
  # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.16
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
||||||| parent of a330f96... message
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
  matrix:
    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-lts-2.16
    - EMBER_TRY_SCENARIO=ember-release
    - EMBER_TRY_SCENARIO=ember-beta
    - EMBER_TRY_SCENARIO=ember-canary
    - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
=======
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      script:
        - npm run lint:hbs
        - npm run lint:js
        - npm test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
    - env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
>>>>>>> a330f96... message
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery

before_install:
  - npm config set spin false
  - npm install -g npm@^5.7
  - npm --version

install:
  - npm ci

before_script:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox

script:
<<<<<<< HEAD
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/eslint '**/*.js'
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
||||||| parent of a330f96... message
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup
=======
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
>>>>>>> a330f96... message
